export const categories = [
  'Двигатель',
  'Подвеска',
  'Тормозная система',
  'Электрооборудование',
  'Кузовные детали',
  'Фильтры',
  'Масла и жидкости',
];

export const brands = [
  'Mann',
  'Bosch',
  'Kayaba',
  'NGK',
  'Volkswagen',
  'Mobil',
];

export const products = [
  {
    id: 1,
    name: 'Масляный фильтр Mann',
    brand: 'Mann',
    category: 'Фильтры',
    description: 'Высококачественный масляный фильтр для легковых автомобилей.',
    price: 18,
    img: 'https://cdn1.ozone.ru/s3/multimedia-v/6249614131.jpg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': 'W 914/2',
      'Высота': '123 мм',
      'Диаметр': '76 мм',
    },
    rating: 4.5,
    reviews: [],
  },
  {
    id: 2,
    name: 'Тормозные колодки Bosch',
    brand: 'Bosch',
    category: 'Тормозная система',
    description: 'Комплект передних тормозных колодок для иномарок.',
    price: 55,
    img: 'https://avatars.mds.yandex.net/get-mpic/5242361/img_id7285974187815219037.jpeg/orig',
    isNew: false,
    isSale: true,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': '0 986 424 795',
      'Толщина': '17 мм',
      'Материал': 'Полуметалл',
    },
    rating: 4.8,
    reviews: [],
  },
  {
    id: 3,
    name: 'Амортизатор Kayaba',
    brand: 'Kayaba',
    category: 'Подвеска',
    description: 'Надежный амортизатор для комфортной езды.',
    price: 120,
    img: 'https://ravta.ru/upload/iblock/e94/e942f3ee426b3a27643cb45063951a53.JPG',
    isNew: true,
    isSale: false,
    isTop: false,
    inStock: false,
    specs: {
      'Артикул': '343219',
      'Длина': '540 мм',
      'Тип': 'Масляный',
    },
    rating: 4.2,
    reviews: [],
  },
  {
    id: 4,
    name: 'Свеча зажигания NGK',
    brand: 'NGK',
    category: 'Электрооборудование',
    description: 'Свеча зажигания для бензиновых двигателей.',
    price: 10,
    img: 'https://main-cdn.sbermegamarket.ru/big1/hlr-system/-79/974/651/910/221/03/600022455962b0.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': 'BKR6E',
      'Резьба': '14 мм',
      'Длина': '19 мм',
    },
    rating: 4.7,
    reviews: [],
  },
  {
    id: 5,
    name: 'Капот для VW Passat',
    brand: 'Volkswagen',
    category: 'Кузовные детали',
    description: 'Оригинальный капот для Volkswagen Passat B6.',
    price: 350,
    img: 'https://avtograde.ru/46504-thickbox_default/kapot-volkswagen-passat-b6.jpg',
    isNew: false,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': '3C0823031A',
      'Материал': 'Сталь',
      'Цвет': 'Грунт',
    },
    rating: 4.9,
    reviews: [],
  },
  {
    id: 6,
    name: 'Моторное масло Mobil 5W-40',
    brand: 'Mobil',
    category: 'Масла и жидкости',
    description: 'Синтетическое моторное масло для современных двигателей.',
    price: 60,
    img: 'https://main-cdn.sbermegamarket.ru/big2/hlr-system/123/368/154/832/816/20/600011375676b0.png',
    isNew: true,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Объем': '4 л',
      'Вязкость': '5W-40',
      'Тип': 'Синтетика',
    },
    rating: 4.6,
    reviews: [],
  },
  {
    id: 7,
    name: 'Воздушный фильтр Bosch',
    brand: 'Bosch',
    category: 'Фильтры',
    description: 'Воздушный фильтр для бензиновых двигателей.',
    price: 25,
    img: 'https://cdn1.ozone.ru/s3/multimedia-t/6167595689.jpg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': 'F 026 400 330',
      'Высота': '45 мм',
      'Длина': '270 мм',
    },
    rating: 4.4,
    reviews: [],
  },
  {
    id: 8,
    name: 'Топливный фильтр Mann',
    brand: 'Mann',
    category: 'Фильтры',
    description: 'Топливный фильтр для дизельных двигателей.',
    price: 35,
    img: 'https://autosnab73.ru/images/detailed/1110/6011012367.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': 'WK 842/10',
      'Высота': '85 мм',
      'Диаметр': '65 мм',
    },
    rating: 4.3,
    reviews: [],
  },
  {
    id: 9,
    name: 'Тормозной диск Brembo',
    brand: 'Bosch',
    category: 'Тормозная система',
    description: 'Вентилируемый тормозной диск для легковых автомобилей.',
    price: 85,
    img: 'https://avatars.mds.yandex.net/get-mpic/5238069/img_id7641319954389198417.jpeg/orig',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': '09.9762.10',
      'Диаметр': '280 мм',
      'Толщина': '22 мм',
    },
    rating: 4.7,
    reviews: [],
  },
  {
    id: 10,
    name: 'Аккумулятор Bosch S5',
    brand: 'Bosch',
    category: 'Электрооборудование',
    description: 'Необслуживаемый аккумулятор для современных автомобилей.',
    price: 220,
    img: 'https://www.1profshop.ru/upload/iblock/f04/f04538d0fb41a472185d03a48f2fa2db.png',
    isNew: false,
    isSale: true,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': '0 092 S5 005',
      'Емкость': '60 Ач',
      'Пусковой ток': '540 А',
    },
    rating: 4.8,
    reviews: [],
  },
  {
    id: 11,
    name: 'Масляный фильтр Bosch',
    brand: 'Bosch',
    category: 'Фильтры',
    description: 'Высококачественный масляный фильтр для дизельных двигателей.',
    price: 22,
    img: 'https://cdn1.ozone.ru/s3/multimedia-h/c400/6036091745.jpg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': '0 451 103 316',
      'Высота': '120 мм',
      'Диаметр': '75 мм',
    },
    rating: 4.6,
    reviews: [],
  },
  {
    id: 12,
    name: 'Передний амортизатор Kayaba',
    brand: 'Kayaba',
    category: 'Подвеска',
    description: 'Передний амортизатор для легковых автомобилей.',
    price: 95,
    img: 'https://cdn.izap24.ru/images/prodacts/sourse/181267/181267915_kyb-amortizatoryi-perednyaya-renault-scenic-ii-grand-sce.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': '343220',
      'Длина': '520 мм',
      'Тип': 'Газомасляный',
    },
    rating: 4.4,
    reviews: [],
  },
  {
    id: 13,
    name: 'Свеча зажигания NGK Platinum',
    brand: 'NGK',
    category: 'Электрооборудование',
    description: 'Платиновая свеча зажигания для современных двигателей.',
    price: 15,
    img: 'https://ir.ozone.ru/s3/multimedia-k/c1000/6132861728.jpg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': 'PFR6Q',
      'Резьба': '14 мм',
      'Длина': '19 мм',
    },
    rating: 4.9,
    reviews: [],
  },
  {
    id: 14,
    name: 'Бампер для VW Golf',
    brand: 'Volkswagen',
    category: 'Кузовные детали',
    description: 'Передний бампер для Volkswagen Golf 7.',
    price: 280,
    img: 'https://vonard-tuning.ru/upload/iblock/fa5/image_1L0807103JR3_1.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': '5G0807107',
      'Материал': 'Пластик',
      'Цвет': 'Грунт',
    },
    rating: 4.7,
    reviews: [],
  },
  {
    id: 15,
    name: 'Трансмиссионное масло Mobil 75W-90',
    brand: 'Mobil',
    category: 'Масла и жидкости',
    description: 'Синтетическое трансмиссионное масло для КПП.',
    price: 45,
    img: 'https://i.ebayimg.com/images/g/Gs8AAOSwLRVjibH4/s-l1600.jpg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Объем': '1 л',
      'Вязкость': '75W-90',
      'Тип': 'Синтетика',
    },
    rating: 4.8,
    reviews: [],
  },
  {
    id: 16,
    name: 'Тормозная жидкость Bosch DOT4',
    brand: 'Bosch',
    category: 'Тормозная система',
    description: 'Тормозная жидкость DOT4 для всех типов тормозных систем.',
    price: 12,
    img: 'https://basket-12.wbbasket.ru/vol1800/part180005/180005683/images/big/1.webp',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Объем': '0.5 л',
      'Точка кипения': '230°C',
      'Стандарт': 'DOT4',
    },
    rating: 4.5,
    reviews: [],
  },
  {
    id: 17,
    name: 'Ремень ГРМ Gates',
    brand: 'Bosch',
    category: 'Двигатель',
    description: 'Ремень ГРМ для бензиновых двигателей.',
    price: 65,
    img: 'https://avatars.mds.yandex.net/get-mpic/4119563/img_id2304547466363201860.jpeg/orig',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': 'K015381XS',
      'Длина': '120 зубьев',
      'Ширина': '25 мм',
    },
    rating: 4.7,
    reviews: [],
  },
  {
    id: 18,
    name: 'Масляный насос Mann',
    brand: 'Mann',
    category: 'Двигатель',
    description: 'Масляный насос для бензиновых двигателей.',
    price: 180,
    img: 'https://img.rain-auto.ru/articles/000344223.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': 'P 74-100',
      'Производительность': '45 л/мин',
      'Давление': '5 бар',
    },
    rating: 4.6,
    reviews: [],
  },
  {
    id: 19,
    name: 'Передняя пружина Kayaba',
    brand: 'Kayaba',
    category: 'Подвеска',
    description: 'Передняя пружина подвески для легковых автомобилей.',
    price: 85,
    img: 'https://avatars.mds.yandex.net/get-mpic/1866068/2a0000018af53675eb5e2968157639370b53/orig',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': 'SK3432',
      'Диаметр': '12 мм',
      'Количество витков': '6.5',
    },
    rating: 4.5,
    reviews: [],
  },
  {
    id: 20,
    name: 'Катушка зажигания NGK',
    brand: 'NGK',
    category: 'Электрооборудование',
    description: 'Катушка зажигания для современных двигателей.',
    price: 75,
    img: 'https://avatars.mds.yandex.net/get-mpic/7721414/img_id4607739313109603861.jpeg/orig',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': 'U5051',
      'Напряжение': '12V',
      'Тип': 'Цифровая',
    },
    rating: 4.8,
    reviews: [],
  },
  {
    id: 21,
    name: 'Крыло для VW Polo',
    brand: 'Volkswagen',
    category: 'Кузовные детали',
    description: 'Переднее крыло для Volkswagen Polo.',
    price: 150,
    img: 'https://autopiter.kz/static2/detailphoto/w2000/P948/STVWP60161-1.JPG',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': '6R0821011',
      'Материал': 'Сталь',
      'Цвет': 'Грунт',
    },
    rating: 4.6,
    reviews: [],
  },
  {
    id: 22,
    name: 'Охлаждающая жидкость Mobil',
    brand: 'Mobil',
    category: 'Масла и жидкости',
    description: 'Антифриз для системы охлаждения.',
    price: 25,
    img: 'https://static.avtobiznes.by/media/v3_products/zhidkosti_ohlazhdajuschije/Mobil/Mobil-151154R-1.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Объем': '5 л',
      'Температура': '-40°C',
      'Цвет': 'Зеленый',
    },
    rating: 4.7,
    reviews: [],
  },
  {
    id: 23,
    name: 'Тормозной суппорт Bosch',
    brand: 'Bosch',
    category: 'Тормозная система',
    description: 'Передний тормозной суппорт для легковых автомобилей.',
    price: 120,
    img: 'https://file.euroauto.ru/v2/file/parts/new/2131372/1.jpg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': '0 986 348 016',
      'Тип': 'Плавающий',
      'Материал': 'Алюминий',
    },
    rating: 4.9,
    reviews: [],
  },
  {
    id: 24,
    name: 'Ремень генератора Gates',
    brand: 'Bosch',
    category: 'Двигатель',
    description: 'Ремень привода вспомогательных агрегатов.',
    price: 35,
    img: 'https://ir.ozone.ru/s3/multimedia-6/c1000/6612444258.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': '6PK1190',
      'Длина': '1190 мм',
      'Ширина': '6 ребер',
    },
    rating: 4.5,
    reviews: [],
  },
  {
    id: 25,
    name: 'Топливный насос Mann',
    brand: 'Mann',
    category: 'Двигатель',
    description: 'Топливный насос для бензиновых двигателей.',
    price: 95,
    img: 'https://main-cdn.sbermegamarket.ru/big1/hlr-system/1485909722/600000335807b0.jpeg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': 'P 74-200',
      'Производительность': '120 л/ч',
      'Давление': '3 бар',
    },
    rating: 4.7,
    reviews: [],
  },
  {
    id: 26,
    name: 'Задний амортизатор Kayaba',
    brand: 'Kayaba',
    category: 'Подвеска',
    description: 'Задний амортизатор для легковых автомобилей.',
    price: 85,
    img: 'https://cdn1.ozone.ru/s3/multimedia-1-a/6940006282.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': '343221',
      'Длина': '510 мм',
      'Тип': 'Газомасляный',
    },
    rating: 4.6,
    reviews: [],
  },
  {
    id: 27,
    name: 'Свеча накаливания NGK',
    brand: 'NGK',
    category: 'Электрооборудование',
    description: 'Свеча накаливания для дизельных двигателей.',
    price: 18,
    img: 'https://cdn1.ozone.ru/s3/multimedia-i/6509935374.jpg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Артикул': 'Y-103J',
      'Напряжение': '12V',
      'Длина': '108 мм',
    },
    rating: 4.8,
    reviews: [],
  },
  {
    id: 28,
    name: 'Капот для VW Golf',
    brand: 'Volkswagen',
    category: 'Кузовные детали',
    description: 'Капот для Volkswagen Golf 7.',
    price: 320,
    img: 'https://fdparts.ru/parts_img2/big/55def2805d2ba00c3a8aa0ba7929b6a7.jpg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': '5G0823021',
      'Материал': 'Сталь',
      'Цвет': 'Грунт',
    },
    rating: 4.7,
    reviews: [],
  },
  {
    id: 29,
    name: 'Тормозная жидкость Mobil DOT4',
    brand: 'Mobil',
    category: 'Масла и жидкости',
    description: 'Тормозная жидкость DOT4 для всех типов тормозных систем.',
    price: 15,
    img: 'https://cdn1.ozone.ru/s3/multimedia-1-7/7109610415.jpg',
    isNew: true,
    isSale: false,
    isTop: true,
    inStock: true,
    specs: {
      'Объем': '1 л',
      'Точка кипения': '230°C',
      'Стандарт': 'DOT4',
    },
    rating: 4.9,
    reviews: [],
  },
  {
    id: 30,
    name: 'Тормозной цилиндр Bosch',
    brand: 'Bosch',
    category: 'Тормозная система',
    description: 'Главный тормозной цилиндр для легковых автомобилей.',
    price: 75,
    img: 'https://photos.autorus.ru/upload/60/a7/0a/60a70aa0-f11f-4c16-98d0-0382a8d7cef1.jpeg',
    isNew: false,
    isSale: true,
    isTop: false,
    inStock: true,
    specs: {
      'Артикул': '0 986 478 001',
      'Диаметр': '22.2 мм',
      'Тип': 'Двухконтурный',
    },
    rating: 4.6,
    reviews: [],
  }
]; 